name: Run UnitTest

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'changes/**'
      - 'deploy/**'
      - '**.md'
      - '**.yml'
      - '**.xml'
      - 'LICENSE'
      - '.gitignore'

jobs:
  Run-Go-CI:
    name: Run Go Agent CI
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DONGTAI_WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：项目${{github.repository}}构建开始\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'

  Test-Agent:
    name: Update this repo's README
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.16', '1.15', '1.14', '1.13', '1.12', '1.11' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }} # T

      - run: bash .github/workflows/scripts/run-govwa.sh

  Finish-Go-CI:
    name: Finish Go CI
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - Test-Agent
    steps:
      - uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DONGTAI_WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：项目${{github.repository}}构建开始\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'

