name: Run UnitTest

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'changes/**'
      - 'deploy/**'
      - '**.md'
      - '**.yml'
      - '**.xml'
      - 'LICENSE'
      - '.gitignore'

jobs:
  Test-Agent:
    name: Update this repo's README
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.17', '1.16', '1.15', '1.14', '1.13', '1.12', '1.11' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }} # T

      - run: bash .github/workflows/scripts/run-govwa.sh
